### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by TotallyNotAHaxxer** [sw33tLie/bbscope#18]
use YAML files, parsing and making YAML is probs the easiest thing in the world and way easier than using flags to set API keys and API tokens 

something as simple as this would work

```yaml
api_key_SHODAN:
    Key: "YOUR API KEY HERE"

api_key_knoxss:
    Key: "YOUR API KEY HERE"
```

then just simply parse it and return the data in go, really is not that hard and would be better for user end experience
